local keymap = vim.keymap;
keymap.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })
keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
keymap.set('n', 'x', '"_x')
keymap.set('n', '+', '<C-a>')
keymap.set('n', '-', '<C-x>')
keymap.set('n', '<left>', '<C-w><')
keymap.set('n', '<right>', '<C-w>>')
keymap.set('n', '<up>', '<C-w>+')
keymap.set('n', '<down>', '<C-w>-')
keymap.set('n', '<left>', ':vertical resize -10<Return>')
keymap.set('n', '<right>', ':vertical resize +10<Return>')
keymap.set('n', '<up>', ':resize +10<Return>')
keymap.set('n', '<down>', ':resize -10<Return>')
keymap.set('n', '<leader>ex', vim.cmd.Ex)
keymap.set('n', '[d', vim.diagnostic.goto_prev)
keymap.set('n', ']d', vim.diagnostic.goto_next)
keymap.set('n', '<leader>e', vim.diagnostic.open_float)
keymap.set('n', '<leader>q', vim.diagnostic.setloclist)
