local keymap = vim.keymap;
keymap.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })
keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
keymap.set('n', 'x', '"_x')
keymap.set('n', '+', '<C-a>')
keymap.set('n', '-', '<C-x>')
keymap.set('n', 'sh', '<C-w>h')
keymap.set('n', 'sj', '<C-w>j')
keymap.set('n', 'sk', '<C-w>k')
keymap.set('n', 'sl', '<C-w>l')
keymap.set('n', '<left>', ':vertical resize -1<Return>')
keymap.set('n', '<right>', ':vertical resize +1<Return>')
keymap.set('n', '<up>', ':resize +1<Return>')
keymap.set('n', '<down>', ':resize -1<Return>')
keymap.set('n', '<leader>ex', vim.cmd.Ex)
keymap.set('n', '[d', vim.diagnostic.goto_prev)
keymap.set('n', ']d', vim.diagnostic.goto_next)
keymap.set('n', '<leader>ee', vim.diagnostic.open_float)
keymap.set('n', '<leader>q', vim.diagnostic.setloclist)
